baseURL = 'https://blog.hmszeit.me/ConfidentlyIncorrect'
title = 'Confidently Incorrect'


[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

# （可選）明確宣告 taxonomy
[taxonomies]
  tag = "tags"
  category = "categories"

# Search 需要輸出 JSON 索引
[outputs]
  home = ["HTML", "RSS", "JSON"]

#（可選）Search 的 Fuse.js 參數
[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ["title", "permalink", "summary", "content"]

[params.homeInfoParams]
Title = "Here are..."
Content = """
* **Thoughts, observations, and murmurs** about my daily life. 

* It also serves as an archive of my past experiences.

* Everyone is welcome.
"""
[params]
  [[params.socialIcons]]
    name  = "github"
    title = "View Source on Github"
    url   = "https://github.com/hmsyuan/ConfidentlyIncorrect"

  [[params.socialIcons]]
    name  = "Facebook"
    title = "View Facebook Profile"
    url   = "https://www.facebook.com/mingsyuan.ho/"

# [[params.socialIcons]]
#    name  = "X"
#    title = "Share PaperMod on X/Twitter"
#    url   = "https://x.com/intent/tweet/?text=Checkout%20Hugo%20PaperMod%20%E2%9C%A8%0AA%20fast,%20clean,%20responsive%20Hugo%20theme.&url=https://github.com/adityatelange/hugo-PaperMod&hashtags=Hugo,PaperMod"

#  [[params.socialIcons]]
#    name  = "Bluesky"
#    title = "Bluesky :)"
#    url   = "https://ko-fi.com/adityatelange"

[menu]
  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 10
 
 [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 30

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 40

  [[menu.main]]
    identifier = "Test1"
    name = "Test1"
    url = "/posts/Test1"
    weight = 50